<?php

namespace ContainerOn9stgi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJWTDecoratorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\OpenApi\JWTDecorator' shared autowired service.
     *
     * @return \App\OpenApi\JWTDecorator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/OpenApi/Factory/OpenApiFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/OpenApi/JwtDecorator.php';

        return $container->privates['App\\OpenApi\\JWTDecorator'] = new \App\OpenApi\JWTDecorator(($container->privates['App\\OpenApi\\JWTDecorator.inner'] ?? $container->load('getJWTDecorator_InnerService')));
    }
}
