<?php

namespace Container804n597;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupeProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\GroupeProcessor' shared autowired service.
     *
     * @return \App\State\GroupeProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/State/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/State/GroupeProcessor.php';

        return $container->privates['App\\State\\GroupeProcessor'] = new \App\State\GroupeProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
