<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0xLsJIK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0xLsJIK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0xLsJIK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0xLsJIK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0xLsJIK\App_KernelDevDebugContainer([
    'container.build_hash' => '0xLsJIK',
    'container.build_id' => 'af4b43a6',
    'container.build_time' => 1669907289,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0xLsJIK');
